#+title: Task list

This is a list of things that I want to include in the in the project or how I think things should work or look.

* Screens
** Home
Here the user should be shown most relevant items. Things that you're most likely are here for when you open the program.

That includes:
- List of channels that have new videos
- List of categories which have new videos

Those should display relevant videos and have ability to go to detail page about each

** Playlist history
When all videos of a playlist are marked as watched, it gets moved here from the tracker

** Channel tracker
A screen with a list of groups on the side, with ability to add more groups. In the middle, there will be a list of tracked channels with the top having ability to add more by url.

Each group should have a toggle for whatever to track new videos on the home page or not for it.

** Channel view
When clicked on, a channel information will be displayed with options to assign it to a group or multiple groups. A list of recent videos will be shown, as well as a list of playlists.

* Additional features
** ani-cli like functionality
This would pretty much work like ani-cli but for youtube as is, and with graphical interface. Why not implement adding support for adding animes from streaming sites to the playlist tracker? Maybe even any show from any additional services.

** Other video sites
Odysee and Rumble among others would be neat addition. One app to watch them all.

* Task List
** More information
- [ ] Playlist should display the information for when they were last updated or first created
** More convenient playlist management
- [ ] Ability to mass set videos as watched (button to set last watched)
** Settings
- [ ] Set whatever newly added playlists should be tracked by default
- [ ] Set where the control bar should be located (left right top bottom)
- [ ] Set where controls should be located (left right)
** UI
- [ ] Playlist History page where fully watched playlists should go
- [ ] Ability to sort playlists in the tracker screen
- [ ] Divide playlist detail screen into tabs with watched and unwatched videos and all videos
** Code
- [ ] Test if updating videos or thumbnails especially, only when they are about to be displayed would work better for avoiding hangups
